// Statyczna mapa działów (2 pierwsze cyfry) Nomenklatury Scalonej (CN/HS) —
// standard WCO, ten sam dla całego świata. Używana wyłącznie do pokazania
// orientacyjnego opisu "czego dotyczy ten kod celny" obok pola Kod CN/HS w
// module Wyceny — NIE zastępuje weryfikacji w ISZTAR, tylko pomaga zespołowi
// od razu zobaczyć, czy kod "ma sens" dla wpisanego towaru.
export const HS_CHAPTERS = {
  '01': 'Zwierzęta żywe',
  '02': 'Mięso i podroby jadalne',
  '03': 'Ryby i skorupiaki',
  '04': 'Produkty mleczarskie, jaja, miód',
  '05': 'Produkty pochodzenia zwierzęcego, gdzie indziej niewymienione',
  '06': 'Żywe drzewa i rośliny, kwiaty cięte',
  '07': 'Warzywa',
  '08': 'Owoce i orzechy jadalne',
  '09': 'Kawa, herbata, przyprawy',
  '10': 'Zboża',
  '11': 'Produkty przemysłu młynarskiego',
  '12': 'Nasiona oleiste, ziarna, słoma',
  '13': 'Ekstrakty roślinne, żywice',
  '14': 'Materiały roślinne do wyplatania',
  '15': 'Tłuszcze i oleje zwierzęce/roślinne',
  '16': 'Przetwory z mięsa, ryb',
  '17': 'Cukry i wyroby cukiernicze',
  '18': 'Kakao i przetwory z kakao',
  '19': 'Przetwory ze zbóż, mąki, mleka, pieczywo',
  '20': 'Przetwory z warzyw, owoców',
  '21': 'Różne przetwory spożywcze',
  '22': 'Napoje, alkohole, ocet',
  '23': 'Odpady i pasze dla zwierząt',
  '24': 'Tytoń i wyroby tytoniowe',
  '25': 'Sól, siarka, ziemia, kamień, cement',
  '26': 'Rudy metali, żużle, popioły',
  '27': 'Paliwa mineralne, oleje, wosk mineralny',
  '28': 'Chemikalia nieorganiczne',
  '29': 'Chemikalia organiczne',
  '30': 'Produkty farmaceutyczne',
  '31': 'Nawozy',
  '32': 'Barwniki, farby, lakiery',
  '33': 'Olejki eteryczne, kosmetyki, perfumy',
  '34': 'Mydła, środki piorące, świece, woski',
  '35': 'Substancje białkowe, kleje, enzymy',
  '36': 'Materiały wybuchowe, wyroby pirotechniczne, zapałki',
  '37': 'Materiały fotograficzne i filmowe',
  '38': 'Produkty chemiczne różne',
  '39': 'Tworzywa sztuczne i wyroby z nich',
  '40': 'Kauczuk i wyroby z kauczuku',
  '41': 'Skóry i skórki surowe',
  '42': 'Wyroby ze skóry, galanteria skórzana',
  '43': 'Futra i wyroby futrzarskie',
  '44': 'Drewno i wyroby z drewna',
  '45': 'Korek i wyroby z korka',
  '46': 'Wyroby ze słomy, wikliny, plecionkarskie',
  '47': 'Masa włóknista z drewna, papier makulaturowy',
  '48': 'Papier, karton i wyroby z nich',
  '49': 'Książki, gazety, druki',
  '50': 'Jedwab',
  '51': 'Wełna, sierść zwierzęca',
  '52': 'Bawełna',
  '53': 'Pozostałe włókna roślinne, przędza papierowa',
  '54': 'Włókna chemiczne ciągłe',
  '55': 'Włókna chemiczne odcinkowe',
  '56': 'Wata, filc, włókniny, liny, sznury',
  '57': 'Dywany i pozostałe pokrycia podłogowe',
  '58': 'Tkaniny specjalne, hafty, koronki',
  '59': 'Tkaniny impregnowane, powlekane, techniczne',
  '60': 'Dzianiny',
  '61': 'Odzież i dodatki odzieżowe dziane',
  '62': 'Odzież i dodatki odzieżowe niedziane',
  '63': 'Pozostałe konfekcjonowane wyroby włókiennicze, odzież używana',
  '64': 'Obuwie',
  '65': 'Nakrycia głowy',
  '66': 'Parasole, laski',
  '67': 'Pióra, kwiaty sztuczne, wyroby z włosów',
  '68': 'Wyroby z kamienia, gipsu, cementu, azbestu',
  '69': 'Wyroby ceramiczne',
  '70': 'Szkło i wyroby ze szkła',
  '71': 'Perły, kamienie i metale szlachetne, biżuteria',
  '72': 'Żeliwo i stal',
  '73': 'Wyroby z żeliwa lub stali',
  '74': 'Miedź i wyroby z miedzi',
  '75': 'Nikiel i wyroby z niklu',
  '76': 'Aluminium i wyroby z aluminium',
  '78': 'Ołów i wyroby z ołowiu',
  '79': 'Cynk i wyroby z cynku',
  '80': 'Cyna i wyroby z cyny',
  '81': 'Pozostałe metale nieszlachetne',
  '82': 'Narzędzia, sztućce z metali nieszlachetnych',
  '83': 'Różne wyroby z metali nieszlachetnych (zamki, okucia, kłódki)',
  '84': 'Maszyny, urządzenia mechaniczne, komputery',
  '85': 'Maszyny i urządzenia elektryczne, elektronika, AGD',
  '86': 'Lokomotywy, tabor kolejowy',
  '87': 'Pojazdy nieszynowe (samochody, przyczepy, rowery)',
  '88': 'Statki powietrzne, kosmiczne',
  '89': 'Statki, łodzie, konstrukcje pływające',
  '90': 'Przyrządy optyczne, pomiarowe, medyczne',
  '91': 'Zegary i zegarki',
  '92': 'Instrumenty muzyczne',
  '93': 'Broń i amunicja',
  '94': 'Meble, oświetlenie, budynki prefabrykowane',
  '95': 'Zabawki, gry, artykuły sportowe',
  '96': 'Wyroby różne (szczotki, guziki, długopisy, parasolki plażowe)',
  '97': 'Dzieła sztuki, antyki',
}

// Zwraca krótki opis kategorii na podstawie pierwszych 2 cyfr wpisanego kodu
// CN/HS (akceptuje kod z kropkami/spacjami, np. "9406.10.00" albo "940610").
export function describeHsCode(code) {
  if (!code) return null
  const digits = String(code).replace(/\D/g, '')
  if (digits.length < 2) return null
  return HS_CHAPTERS[digits.slice(0, 2)] || null
}
